### ISSUE TITLE
Unable to get the role of the account

### ISSUE THREAD

**Issue by Gautamshahi** [liuqingli/TwiRole#4]
Hi, I am not getting the role of the account, I am passing a csv file., Can you please explain the issue?

![image](https://user-images.githubusercontent.com/3966230/90333198-2c6ac400-dfc4-11ea-8a4c-88b4d3dcaceb.png)

**Comment by liuqingli** [comment]
Hey, could you please share your csv file with me? Does this issue occur after a number of iterations?
